### ISSUE TITLE
get_cat_variables inquiry

### ISSUE THREAD

**Issue by iamamiramine** [schneiderkamplab/syntheval#10]
in `get_cat_variables` in **variable_detection.py** in the **utils** folder, it checks if the column dtype is **object**, then it appends it to the `cat_variabes` list, which is the list of categorical features of my dataset. I want to ask why does it also check for dtypes **int64** and **float64**? Aren't those supposed to belong to the list of numerical features which is the `num_cols` list?

**Comment by THyrup** [comment]
Hi @iamamiramine,
Thank you for reaching out!

It is very common to represent categorical values using numerical values through, for example, one-hot, binary, or ordinal encoding. While syntactically these attributes are numerical, they should not be interpreted as their numerical representative.

In the function `get_cat_variables`, an assumption is made that if an attribute contains few unique values, they are more likely to be numerical representations of categorical variable than actual numerical attributes and, therefore, should be treated differently. By default, the threshold for interpreting an attribute as categorical is set to less than 10 unique values, but can be changed when initializing a `SynthEval` instance using the `unique_threshold` parameter.

I hope this addresses your question sufficiently.

**Comment by iamamiramine** [comment]
Thank you for your reply!
So if I have a dataset that consists of categorical features only, then metrics such as **Propensity Mean Squared Error** will not work on my dataset, even if I encoded them using Ordinal Encoding for example. Did I understand correctly?

**Comment by THyrup** [comment]
Hi @iamamiramine,

Propensity Mean Squared Error and most other metrics should work regardless of the variable compositions. However, after double checking I noticed an oversight in the implementation causing errors when the data only contained categorical variables.

The issue should be resolved now.

Please don't hesitate to reach out if it doesn't work as expected.

**Comment by iamamiramine** [comment]
Thank you so much for your help!
