### ISSUE TITLE
Metrics interpretation

### ISSUE THREAD

**Issue by iamamiramine** [schneiderkamplab/syntheval#12]
May I ask if there is any guide or documentation on how to interpret the metrics? For example I am trying to figure out weather a higher score in Nearest Neighbour Adversarial Accuracy represents higher similarity between my synthetic and real data, and vice versa.
Or is it possible to provide a list of references to the original proposals of the metrics?
Thank you!

**Comment by THyrup** [comment]
Hi @iamamiramine,

The paper connected to SynthEval presents the currently implemented metrics in the appendix including references to original proposals. You can find the paper here: [SynthEval: A Framework for Detailed Utility and Privacy Evaluation of Tabular Synthetic Data](https://arxiv.org/abs/2404.15821).

**Comment by iamamiramine** [comment]
Thank you!
